# Generated by Django 4.1 on 2022-08-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='publicado_comenatio',
            new_name='publicado_comentario',
        ),
    ]
